services:
  web:
    build: ./backend
    command: uv run uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 4000
    volumes:
      - ./backend:/app/
    ports:
      - 4000:4000
  
      

